-- 1. Creazione del Database
CREATE DATABASE IF NOT EXISTS COOKIT;
USE COOKIT;

-- 2. TABELLA UTENTI (L'entità principale da cui tutto dipende)
CREATE TABLE UTENTI (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cognome VARCHAR(100) NOT NULL,
    Immagine_Profilo LONGTEXT, 
    Data_Nascita DATE NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,      -- Nuovo campo aggiunto
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Data_Iscrizione TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABELLA PONTE: FOLLOWERS (Dipende solo da UTENTI)
CREATE TABLE FOLLOWERS (
    Follower_Id INT NOT NULL,  
    Followed_Id INT NOT NULL,  
    Data_Seguito TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Follower_Id, Followed_Id),
    FOREIGN KEY (Follower_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE,
    FOREIGN KEY (Followed_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);

-- 4. TABELLA RICETTE (Dipende da UTENTI)
CREATE TABLE RICETTE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Utente_Id INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Immagine LONGTEXT, 
    Ingredienti JSON NOT NULL, 
    Preparazione TEXT NOT NULL,
    Data_Pubblicazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);

-- 5. TABELLA PONTE: LIKES (Dipende da UTENTI e RICETTE)
CREATE TABLE LIKES (
    Utente_Id INT NOT NULL,
    Ricetta_Id INT NOT NULL,
    Data_Like TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Utente_Id, Ricetta_Id),
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE,
    FOREIGN KEY (Ricetta_Id) REFERENCES RICETTE(Id) ON DELETE CASCADE
);

-- 6. TABELLA CARRELLI (Dipende da UTENTI)
CREATE TABLE CARRELLI (
    Utente_Id INT PRIMARY KEY, 
    Lista_Ingredienti JSON NOT NULL,
    Ultimo_Aggiornamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);