DROP DATABASE IF EXISTS COOKIT;
CREATE DATABASE COOKIT;
USE COOKIT;

-- 1. TABELLA UTENTI
CREATE TABLE UTENTI (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cognome VARCHAR(100) NOT NULL,
    Data_Nascita DATE NOT NULL,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Immagine_Profilo LONGTEXT NULL,
    Data_Iscrizione TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABELLA FOLLOWERS
CREATE TABLE FOLLOWERS (
    Follower_Id INT NOT NULL,
    Followed_Id INT NOT NULL,
    Data_Seguito TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Follower_Id, Followed_Id),
    FOREIGN KEY (Follower_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE,
    FOREIGN KEY (Followed_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);

-- 3. TABELLA RICETTE
CREATE TABLE RICETTE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Utente_Id INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Difficolta ENUM('facile', 'medio', 'difficile') NOT NULL,
    Tempo_Preparazione INT NOT NULL,
    Immagine LONGTEXT NULL,
    Ingredienti JSON NOT NULL,
    Preparazione TEXT NOT NULL,
    Data_Pubblicazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);

-- 4. TABELLA LIKES
CREATE TABLE LIKES (
    Utente_Id INT NOT NULL,
    Ricetta_Id INT NOT NULL,
    Data_Like TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Utente_Id, Ricetta_Id),
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE,
    FOREIGN KEY (Ricetta_Id) REFERENCES RICETTE(Id) ON DELETE CASCADE
);

-- 5. TABELLA CARRELLI
CREATE TABLE CARRELLI (
    Utente_Id INT PRIMARY KEY,
    Lista_Ingredienti JSON NOT NULL,
    Ultimo_Aggiornamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);

-- 6. TABELLA COMMENTI
CREATE TABLE COMMENTI (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Ricetta_Id INT NOT NULL,
    Utente_Id INT NOT NULL,
    Testo TEXT NOT NULL,
    Data_Commento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Ricetta_Id) REFERENCES RICETTE(Id) ON DELETE CASCADE,
    FOREIGN KEY (Utente_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE
);

-- 7. TABELLA NOTIFICHE
CREATE TABLE NOTIFICHE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Utente_Destinatario_Id INT NOT NULL, -- Chi riceve l'avviso
    Utente_Attore_Id INT NOT NULL,       -- Chi ha compiuto l'azione
    Tipo ENUM('commento', 'like', 'follow', 'nuova_ricetta') NOT NULL,
    Ricetta_Id INT NULL,                 -- NULL se il tipo è 'follow'
    Letta BOOLEAN DEFAULT FALSE,
    Data_Notifica TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Utente_Destinatario_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE,
    FOREIGN KEY (Utente_Attore_Id) REFERENCES UTENTI(Id) ON DELETE CASCADE,
    FOREIGN KEY (Ricetta_Id) REFERENCES RICETTE(Id) ON DELETE CASCADE
);